#!/bin/bash

INDEX=$1
START_RUN=$2
END_RUN=$3
DATA_OR_SIM=$4
MOMCORR_EL=$5
MOMCORR_PI=$6
CUT_TO_VARY=$7
CUT_STRICTNESS=$8

root -l -b "my_phi6.C+($INDEX,$START_RUN,$END_RUN,$DATA_OR_SIM,$MOMCORR_EL,$MOMCORR_PI,$CUT_TO_VARY,$CUT_STRICTNESS)"
